version: "3.9"

services:
  backend:
    build: ./server
    container_name: server
    ports:
      - "8000:8000"
    expose:
      - "8000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
